### ISSUE TITLE
A couple of issues

### ISSUE THREAD

**Issue by justabuzz** [tsaiDavid/simple-redux-boilerplate#21]
Hi,

This is a great boilerplate to start from. One of the cleanest that I found. I currently have two issues and considering that you have on your agenda to add details on deploying production code and all that then I guess it's user issues.

1) I can't run "npm build prod". I'm getting an error that "\prod\package.json" was not found. Note that if I run the actual commands set for "npm build prod" then things work. I break it to two commands that work on their own:
npm run clean
npm run build:webpack

2) Once I get the generated JS file after build then when trying to run the code I'm getting a JS error "history.listen is not a function". It doesn't happen when I run the code in dev mode. Btw, I see that I'm not the only one having this issue with React/Redux: http://stackoverflow.com/questions/37697950/react-router-redux-history-listen-is-not-a-function

I'd appreciate any assistance with this.

Cheers!

**Comment by juanlizarazo** [comment]
For no. 1 try:

npm run build

npm start and npm test can be run without that run keyboard. There is a list of commands but I can't recall build being one.

So

npm run [script_name]
e.g. 
npm run build
npm run eslint

**Comment by juanlizarazo** [comment]
I'm from my phone, I meant keyword\* not keyboard.

**Comment by justabuzz** [comment]
Hey @juanlizarazo!

Thanks for your reply! I can confirm that the following works:
npm run build

So we just need to figure out that second error! :)

Here's how it looks in my developer tools panel - the error says that listen is not a function. As you can see listen() doesn't exist there:
![image](https://cloud.githubusercontent.com/assets/313585/16524056/ce0f4472-3fe9-11e6-963f-41eb909aef1d.png)

Cheers!

**Comment by justabuzz** [comment]
OK, returning to this code with a fresh set of eyes and I found a typo! Closing the issue :)
